// Code generated by "stringer -type=BuildServerError"; DO NOT EDIT

package buildserver

import "fmt"

const _BuildServerError_name = "NoSuchGroup"

var _BuildServerError_index = [...]uint8{0, 11}

func (i BuildServerError) String() string {
	if i < 0 || i >= BuildServerError(len(_BuildServerError_index)-1) {
		return fmt.Sprintf("BuildServerError(%d)", i)
	}
	return _BuildServerError_name[_BuildServerError_index[i]:_BuildServerError_index[i+1]]
}
