#!/bin/bash

id=build-${RANDOM}
machine="dmerge-${id}"
machinectl clone dmerge:base "${machine}" || exit 1
systemd-nspawn -q -M "${machine}" --bind /usr/portage --bind /var/lib/layman
exec machinectl remove "${machine}"
